name: AR Validate

on:
    push:
        branches:
            - main
        paths-ignore:
            - "dotcom-rendering/**"
    pull_request:
        branches:
            - main
        paths-ignore:
            - "dotcom-rendering/**"

jobs:
    validate:
        name: AR Validate
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - uses: guardian/actions-setup-node@main

            # Cache npm dependencies using https://github.com/bahmutov/npm-install
            # Root dependencies
            - uses: bahmutov/npm-install@v1

            - name: install
              run: yarn --frozen-lockfile

            - name: lint
              working-directory: apps-rendering
              run: yarn lint

            - name: test
              working-directory: apps-rendering
              run: yarn test

            - name: compile client
              working-directory: apps-rendering
              run: yarn build:client:prod

            - name: compile server
              working-directory: apps-rendering
              run: yarn build:server:prod
